<?php $_datatypes_parameters = array (
  0 => 
  array (
    'name' => 'size',
    'label' => 'Size',
    'order' => '1',
    'default_value' => '5',
    'parent' => '18',
    'type' => '18',
    'id' => 1,
    'size' => '',
    'min' => '',
    'max' => '',
    'label_es' => 'Tama&ntilde;o',
    'label_en' => 'Size',
  ),
  1 => 
  array (
    'name' => 'min',
    'label' => 'Minimum',
    'order' => '2',
    'default_value' => '',
    'parent' => '18',
    'type' => '18',
    'id' => 2,
    'label_es' => 'M&iacute;nimo',
    'label_en' => 'Minimum',
  ),
  2 => 
  array (
    'name' => 'max',
    'label' => 'Maximum',
    'order' => '3',
    'default_value' => '',
    'parent' => '18',
    'type' => '18',
    'id' => 3,
    'label_es' => 'M&aacute;ximo',
    'label_en' => 'Maximum',
  ),
  4 => 
  array (
    'name' => 'size',
    'label' => 'Rows',
    'order' => '5',
    'default_value' => '5',
    'parent' => '2',
    'type' => '18',
    'size' => '5',
    'min' => '1',
    'max' => '50',
    'id' => 5,
    'label_es' => 'Filas',
    'label_en' => 'Rows',
  ),
  7 => 
  array (
    'name' => 'size',
    'label' => 'Size',
    'order' => '8',
    'default_value' => '20',
    'parent' => '1',
    'type' => '18',
    'size' => '5',
    'min' => '1',
    'max' => '255',
    'id' => 8,
    'label_es' => 'Tama&ntilde;o',
    'label_en' => 'Size',
  ),
  8 => 
  array (
    'name' => 'entity_id_field',
    'label' => 'Save Entity ID',
    'order' => '9',
    'default_value' => '',
    'parent' => '23',
    'type' => '1',
    'size' => '20',
    'id' => 9,
    'label_es' => 'Guardar ID de Entidad',
    'label_en' => 'Save Entity ID',
  ),
  9 => 
  array (
    'name' => 'field_name_field',
    'label' => 'Save Field Name',
    'order' => '10',
    'default_value' => '',
    'parent' => '23',
    'type' => '1',
    'size' => '20',
    'id' => 10,
    'label_es' => 'Guardar Nombre del Campo',
    'label_en' => 'Save Field Name',
  ),
  10 => 
  array (
    'name' => 'link',
    'label' => 'Link',
    'order' => '11',
    'default_value' => '',
    'parent' => '11',
    'type' => '1',
    'size' => '20',
    'id' => 11,
    'label_es' => 'Enlace',
    'label_en' => 'Link',
  ),
  13 => 
  array (
    'name' => 'hint',
    'label' => 'Hint',
    'order' => '14',
    'default_value' => '',
    'parent' => '22',
    'type' => '24',
    'customview' => 'Gets remote address of the creating user.',
    'customedit' => 'Gets remote address of the creating user.',
    'id' => 14,
    'label_es' => 'Texto de ayuda',
    'label_en' => 'Hint',
  ),
  19 => 
  array (
    'name' => 'related_field_id',
    'label' => 'Entity and Field',
    'order' => '20',
    'default_value' => '',
    'parent' => '7',
    'type' => '23',
    'size' => '20',
    'id' => 20,
    'entity_id_field' => 'related_entity',
    'field_name_field' => 'related_field',
    'table_name_field' => 'related_table',
    'label_es' => 'Entidad y Campo',
    'label_en' => 'Entity and Field',
  ),
  21 => 
  array (
    'name' => 'order_field_id',
    'label' => 'Order Field',
    'order' => '22',
    'default_value' => '',
    'parent' => '7',
    'type' => '25',
    'size' => '20',
    'id' => 22,
    'field_name_field' => 'order_field',
    'fixed_entity' => '',
    'entity_field_id' => 'related_entity',
    'entity_field' => 'related_entity',
    'label_es' => 'Campo de Orden',
    'label_en' => 'Order Field',
  ),
  22 => 
  array (
    'name' => 'size',
    'label' => 'Rows',
    'order' => '23',
    'default_value' => '5',
    'parent' => '16',
    'type' => '18',
    'size' => '5',
    'min' => '1',
    'max' => '50',
    'id' => 23,
    'label_es' => 'Filas',
    'label_en' => 'Rows',
  ),
  26 => 
  array (
    'name' => 'table_name_field',
    'label' => 'Save Table Name',
    'order' => '27',
    'default_value' => '',
    'parent' => '23',
    'type' => '1',
    'size' => '20',
    'id' => 27,
    'label_es' => 'Guardar Nombre de Tabla',
    'label_en' => 'Save Table Name',
  ),
  27 => 
  array (
    'name' => 'field_name_field',
    'label' => 'Save Field Name',
    'order' => '28',
    'default_value' => '',
    'parent' => '25',
    'type' => '1',
    'size' => '20',
    'id' => 28,
    'label_es' => 'Guardar Campo Nombre',
    'label_en' => 'Save Field Name',
  ),
  28 => 
  array (
    'name' => 'fixed_entity',
    'label' => 'Fixed Entity',
    'order' => '29',
    'default_value' => '',
    'parent' => '25',
    'type' => '7',
    'related_field_id' => '114',
    'order_field' => 'name',
    'id' => 29,
    'related_entity' => '1',
    'related_field' => 'name',
    'related_table' => '_entities',
    'label_es' => 'Entidad Fija',
    'label_en' => 'Fixed Entity',
  ),
  29 => 
  array (
    'name' => 'entity_field',
    'label' => 'Depends on',
    'order' => '30',
    'default_value' => '',
    'parent' => '25',
    'type' => '1',
    'size' => '20',
    'id' => 30,
    'field_name_field' => 'entity_field',
    'fixed_entity' => '',
    'entity_field' => 'parent',
    'entity_field_id' => '211',
    'label_es' => 'Depende de',
    'label_en' => 'Depends on',
  ),
  30 => 
  array (
    'name' => 'size',
    'label' => 'Size',
    'order' => '31',
    'default_value' => '40',
    'parent' => '17',
    'type' => '18',
    'size' => '5',
    'min' => '1',
    'max' => '100',
    'id' => 31,
    'label_es' => 'Tama&ntilde;o',
    'label_en' => 'Size',
  ),
  31 => 
  array (
    'name' => 'save_related_name',
    'label' => 'Save Related Name',
    'order' => '32',
    'default_value' => '',
    'parent' => '7',
    'type' => '1',
    'size' => '20',
    'id' => 32,
    'label_es' => 'Guardar Nombre Relacionado',
    'label_en' => 'Save Related Name',
  ),
  32 => 
  array (
    'name' => 'show_menu',
    'label' => 'Mostrar Menu',
    'order' => '33',
    'default_value' => '0',
    'parent' => '16',
    'type' => '13',
    'label_es' => 'Mostrar Menu',
    'label_en' => 'Show Menu',
    'id' => 33,
  ),
  33 => 
  array (
    'name' => 'show_toolbar_undo',
    'label' => 'Mostrar Undo',
    'order' => '34',
    'default_value' => '1',
    'parent' => '16',
    'type' => '13',
    'label_es' => 'Mostrar Undo',
    'label_en' => 'Show Undo',
    'id' => 34,
  ),
  34 => 
  array (
    'name' => 'show_toolbar_copypaste',
    'label' => 'Mostrar Copiar-Pegar',
    'order' => '35',
    'default_value' => '1',
    'parent' => '16',
    'type' => '13',
    'label_es' => 'Mostrar Copiar-Pegar',
    'label_en' => 'Show Copy-Paste',
    'id' => 35,
  ),
  35 => 
  array (
    'name' => 'show_toolbar_basicformat',
    'label' => 'Mostrar Formato B&aacute;sico',
    'order' => '36',
    'default_value' => '1',
    'parent' => '16',
    'type' => '13',
    'label_es' => 'Mostrar Formato B&aacute;sico',
    'label_en' => 'Show Basic Format',
    'id' => 36,
  ),
  36 => 
  array (
    'name' => 'show_toolbar_styleformat',
    'label' => 'Mostrar Formato de Estilo',
    'order' => '37',
    'default_value' => '0',
    'parent' => '16',
    'type' => '13',
    'label_es' => 'Mostrar Formato de Estilo',
    'label_en' => 'Show Style Format',
    'id' => 37,
  ),
  37 => 
  array (
    'name' => 'show_toolbar_align',
    'label' => 'Mostrar Justificado',
    'order' => '38',
    'default_value' => '0',
    'parent' => '16',
    'type' => '13',
    'label_es' => 'Mostrar Justificado',
    'label_en' => 'Show Align',
    'id' => 38,
  ),
  38 => 
  array (
    'name' => 'show_toolbar_lists',
    'label' => 'Mostrar Listas',
    'order' => '39',
    'default_value' => '0',
    'parent' => '16',
    'type' => '13',
    'label_es' => 'Mostrar Listas',
    'label_en' => 'Show Lists',
    'id' => 39,
  ),
  39 => 
  array (
    'name' => 'createButton',
    'label' => '',
    'label_es' => 'Boton Crear',
    'label_en' => 'Create Button',
    'default_value' => '0',
    'parent' => '7',
    'type' => '13',
    'order' => '40',
    'id' => 40,
    'date_modified' => '2020-05-18 03:02',
    'modified_by' => 1,
  ),
  40 => 
  array (
    'name' => 'editButton',
    'label' => '',
    'label_es' => 'Boton Editar',
    'label_en' => 'Edit Button',
    'default_value' => '0',
    'parent' => '7',
    'type' => '13',
    'order' => '41',
    'id' => 41,
    'date_modified' => '2020-05-18 03:03',
    'modified_by' => 1,
  ),
  41 => 
  array (
    'name' => 'allow_free_html',
    'label' => '',
    'label_es' => 'Permitir pegar con formato',
    'label_en' => 'Allow formatted content',
    'default_value' => '0',
    'parent' => '16',
    'type' => '13',
    'order' => '42',
    'id' => 42,
  ),
  42 => 
  array (
    'name' => 'show_toolbar_link',
    'label' => '',
    'label_es' => 'Mostrar Links',
    'label_en' => 'Show Links',
    'default_value' => '0',
    'parent' => '16',
    'type' => '13',
    'order' => '43',
    'id' => 43,
  ),
  43 => 
  array (
    'name' => 'option_list',
    'label' => 'Opciones',
    'label_es' => 'Opciones',
    'label_en' => 'Options',
    'order' => '4',
    'default_value' => '',
    'parent' => '14',
    'type' => '7',
    'related_entity' => '34',
    'related_field_id' => '447',
    'related_field' => 'name',
    'related_table' => '_dropdown_lists',
    'order_field_id' => '447',
    'order_field' => 'name',
    'save_related_name' => '',
    'multiselect' => '0',
    'multiselectfilter' => '0',
    'date_entered' => '2020-05-17 05:21',
    'created_by' => 1,
    'date_modified' => '2020-05-17 05:21',
    'modified_by' => 1,
    'id' => 44,
  ),
  44 => 
  array (
    'name' => 'language',
    'label' => '',
    'label_es' => 'Lenguaje',
    'label_en' => 'Language',
    'order' => '44',
    'default_value' => 'html',
    'parent' => '28',
    'type' => '14',
    'option_list' => '15',
    'date_entered' => '2021-01-21 02:18',
    'created_by' => 1,
    'date_modified' => '2021-01-21 02:19',
    'modified_by' => 1,
    'id' => 45,
    'parent_typename' => 'Code',
    'type_typename' => 'Dropdown',
  ),
  45 => 
  array (
    'name' => 'filter_from',
    'label' => '',
    'label_es' => 'Filtrar desde campo',
    'label_en' => 'Filter from field',
    'order' => 38,
    'default_value' => '',
    'parent' => '7',
    'type' => '1',
    'size' => '20',
    'date_entered' => '2022-03-15 15:23',
    'created_by' => 1,
    'date_modified' => '2022-03-15 15:23',
    'modified_by' => 1,
    'parent_typename' => '',
    'type_typename' => '',
    'id' => 46,
  ),
  46 => 
  array (
    'name' => 'filter_to',
    'label' => '',
    'label_es' => 'Filtrar contra campo',
    'label_en' => 'Filter against field',
    'order' => 39,
    'default_value' => '',
    'parent' => '7',
    'type' => '25',
    'field_name_field' => '',
    'fixed_entity' => '',
    'entity_field' => 'related_entity',
    'date_entered' => '2022-03-15 15:31',
    'created_by' => 1,
    'date_modified' => '2022-03-15 15:31',
    'modified_by' => 1,
    'parent_typename' => '',
    'type_typename' => '',
    'id' => 47,
  ),
  47 => 
  array (
    'name' => 'filter',
    'label' => '',
    'label_es' => 'Filtro',
    'label_en' => 'Filter',
    'order' => 49,
    'default_value' => '',
    'parent' => '7',
    'type' => '1',
    'size' => '40',
    'date_entered' => '2022-05-06 11:39',
    'created_by' => 1,
    'date_modified' => '2022-05-06 11:39',
    'modified_by' => 1,
    'parent_typename' => '',
    'type_typename' => '',
    'id' => 50,
  ),
); ?>